# Generated by Django 4.2.9 on 2024-02-14 20:56

import DataVizUploader.models
import DataVizUploader.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=DataVizUploader.models.FinancialFile.files_directory_path, validators=[DataVizUploader.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['txt', 'doc', 'docx', 'pdf', 'ppt', 'pptx', 'csv'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dependent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('independent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('slope', models.FloatField(blank=True, null=True)),
                ('intercept', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialDataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependent', models.DecimalField(decimal_places=4, max_digits=12)),
                ('independent', models.DecimalField(decimal_places=4, max_digits=12)),
                ('predicted_y', models.DecimalField(decimal_places=4, max_digits=12)),
                ('financial_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataVizUploader.financialfile')),
            ],
        ),
    ]
